# Generated by Django 2.0 on 2017-12-15 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='time',
        ),
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 21, 3, 39, 549320, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='time_of_day',
            field=models.CharField(choices=[('early', 'early'), ('midday', 'midday'), ('afternoon', 'afternoon'), ('evening', 'evening'), ('night', 'night')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='intensity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
