# Generated by Django 2.0 on 2017-12-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20171215_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='day',
            new_name='date',
        ),
    ]
